### ISSUE TITLE
ARM64 error - Unable to find an entry point named 'gst_video_aggregator_get_type' in shared library 'gstvideo-1.0-0.dll'.

### ISSUE THREAD

**Issue by turowicz** [vladkol/gstreamer-netcore#10]
I get the following error when trying to run on ARM:

```
(Argus) Error FileOperationFailed: Connecting to nvargus-daemon failed: No such file or directory (in src/rpc/socket/client/SocketClientDispatch.cpp, function openSocketConnection(), line 205)
(Argus) Error FileOperationFailed: Cannot create camera provider (in src/rpc/socket/client/SocketClientDispatch.cpp, function createCameraProvider(), line 106)
[12:44:04 ERR] The type initializer for 'Orlen.Backend.Service.FrameSources.RealtimeSource' threw an exception.
System.TypeInitializationException: The type initializer for 'Orlen.Backend.Service.FrameSources.RealtimeSource' threw an exception.
---> System.EntryPointNotFoundException: Unable to find an entry point named 'gst_video_aggregator_get_type' in shared library 'gstvideo-1.0-0.dll'.
at Gst.Video.VideoAggregator.gst_video_aggregator_get_type()
at Gst.Video.VideoAggregator.get_GType()
at GtkSharp.GstreamerSharp.ObjectManager.Initialize()
```

Running on Ubuntu 18.04 on ARM64.

cc @vladkol

**Comment by Ronnie-Kelly** [comment]
I suspect that the problem is not ARM.  I have it working on an ARM board running Ubutntu 18.04.
I think the problem might be the version of gstreamer.
The function ‘gst_video_aggregator_get_type’ was introducted in version 1.16 of streamer.
But Ubuntu 18.04 uses version 1.14.5
What worked for me was to download the gstreamer-netcore source, and then revert the gstreamer-sharp branch back to version 1.14.5.  I then built the code again (built against .NET 6).
The resulting library worked fine on my ARM board.

**Comment by turowicz** [comment]
That's correct, the ARM image from NVIDIA (L4T) had a different version of the lib.
