### ISSUE TITLE
DLL Not Found (libgobject-2.0)

### ISSUE THREAD

**Issue by berglie** [vladkol/gstreamer-netcore#4]
The following are installed on Win10:

> MSVC 32-bit (VS 2019, Release CRT)
>     1.18.0 runtime installer
>     1.18.0 development installer

Environment variable is verified to be: 
`GSTREAMER_1_0_ROOT_MSVC_X86 - C:\gstreamer\1.0\msvc_x86\`

On `Gst.Application.Init();` i get the following exception with _gstreamer-sharp-netcore_ **v0.0.8** using .netcore3.1 wpf app:
```
System.DllNotFoundException
  HResult=0x80131524
  Message=GObject: libgobject-2.0-0.dll, libgobject-2.0.so.0, libgobject-2.0.0.dylib, gobject-2.dll
  Source=GLibSharp
  StackTrace:
   at GLibrary.Load(Library library)

```

**Comment by vladkol** [comment]
@berglie gstreamer-netcore doesn't support MSVC builds of GStreamer (because our dependencies from [GtkSharp](https://github.com/GtkSharp/GtkSharp) don't support Gtk libraries shipped with MSVC build of GStreamer. 
You need to install a MiniGW build of GStreamer. 
https://github.com/vladkol/gstreamer-netcore/blob/master/README.md#if-you-develop-on-windows-please-read-this

**Comment by berglie** [comment]
I was suspecting that, however the [gstreamer website](https://gstreamer.freedesktop.org/download/) says: `NOTE: GStreamer-sharp .NET bindings require the MSVC binaries now.`. This should be updated to avoid any confussions. Thank you for your swift reply.

**Comment by vladkol** [comment]
Good point about GStreamer-sharp. This library is based on GStreamer-Sharp source code, but uses different (.NET Core) versions of GtkSharp libraries which still depend on Gtk dlls as they named in MiniGW build of GStreamer.
Eventually, when GStreamer-Sharp adds .NET Core support, this library won’t be needed, but it doesn’t seem to happen soon.
